# Generated by Django 5.1.2 on 2024-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_paid',
            field=models.DateField(blank=True, default='Not Paid!', null=True, verbose_name='Payment Date'),
        ),
    ]
