# Generated by Django 5.1.2 on 2024-10-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_fees_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Returned'),
        ),
    ]
