# Generated by Django 5.1.2 on 2024-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_library_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
