# Generated by Django 5.1.2 on 2024-10-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('office_staff', 'Office Staff')], max_length=20, verbose_name='Role'),
        ),
    ]
